#!/usr/bin/env python3
"""
Convert a .gr network file (as generated by create-graph.py) into
a Graphviz DOT format for easy visualization.

Usage:
    python3 graph_to_dot.py [input-graph] [output-graph]
"""

import sys


def gr_to_dot(input_file, output_file):
  with open(input_file, "r") as f:
    lines = [line.strip() for line in f if line.strip()]

  header = lines[0].split()
  n_vertices = int(header[0])
  n_edges = int(header[1])
  source = int(header[2])
  target = int(header[3])

  # Graphviz
  dot_lines = []
  dot_lines.append("digraph G {")
  dot_lines.append("  rankdir=LR;")
  dot_lines.append("  node [shape=circle, style=filled, fillcolor=lightgrey];")
  dot_lines.append(f"  // Vertices: {n_vertices}, Edges: {n_edges}")
  dot_lines.append(f"  // Source: {source}, Target: {target}")

  dot_lines.append(
      f'  {source} [fillcolor=lightgreen, shape=doublecircle, label="Source ({source})"];'
  )
  dot_lines.append(
      f'  {target} [fillcolor=lightcoral, shape=doublecircle, label="Target ({target})"];'
  )

  # Parse
  for i, line in enumerate(lines[1:], start=0):
    parts = line.split()
    edges = parts[1:]

    for edge in edges:
      dest, cap = edge.strip("()").split(",")
      dest = int(dest)
      cap = int(cap)
      dot_lines.append(f'  {i} -> {dest} [label="{cap}"];')

  dot_lines.append("}")

  with open(output_file, "w") as f:
    f.write("\n".join(dot_lines))

  print(
      f"Converted '{input_file}' to '{output_file}' ({n_vertices} vertices, {n_edges} edges)"
  )


if __name__ == "__main__":
  if len(sys.argv) != 3:
    print("Usage: python3 graph_to_dot.py [input-graph] [output-graph]")
    sys.exit(1)

  input_file = sys.argv[1]
  output_file = sys.argv[2]
  gr_to_dot(input_file, output_file)
